### ISSUE TITLE
Python sdk get requests not returning JSON objects

### ISSUE THREAD

**Issue by nanotellez** [looker-open-source/sdk-codegen#157] opened 2020-01-18 00:51 UTC
Instead of JSON objects, I'm getting objects of type LookWithQuery and Query, for instance. See attached file for an example of the response to a get look request. In short, it is something like 
LookWithQuery(key=value, ...) instead of {key: value}
[Look_response.txt](https://github.com/looker-open-source/sdk-codegen/files/4079784/Look_response.txt)

**Comment by jkaster** [comment] 2020-02-01 02:07
The Python SDK returns a typed object rather than JSON. Is there something you need the raw JSON for?

**Comment by nanotellez** [comment] 2020-02-02 05:42
Well, that was very confusing, since all the looker documentation available says the SDKs ensure that the data received is JSON. And if you want to modify a query, say for instance to change the filter values of a look, you need the entire contents of the query in JSON format so that you can change what needs to be changed and then create a new query (which requires JSON format). Or at least that's my understanding. 

I finally found out that this typed object has a hidden __dict__ attribute, and that allowed me to retrieve the raw JSON and do what I wanted to do (modify filters on a look, as I mentioned above). It ended up being a big workaround... I am not seasoned in looker, but I would think this is a fairly common thing that people might want to do with the API. Particularly those of us building custom Powered-by-Looker web applications. I came out on the other side feeling that there should be a better way to do it.

**Comment by dthorpe** [comment] 2020-02-05 22:43
We still have some rough edges to work out, but our intent is that you should be able to take the result of get_query(), modify it, and pass the modified data as input to create_query().  Read/Modify/Write is a very common coding pattern with the Looker API.  

Providing strongly typed results and params is creating some friction since the type requirements for input are different for output (certain fields REQUIRED on input, but should not be tagged as required on output, differences in nullability, etc).  We're working through this, to find a solution that handles these differences automatically, or if that isn't possible at least a solution that introduces minimal friction for developers writing code.

The downside to working only with raw JSON data is that you don't know in your code editor what properties are available on the object, which ones are required, which ones can be nil, and so forth. You don't get any advice while writing code (code completion, etc), and the code you write fails at runtime when the API rejects your data. We're wanting to provide strong types so that you can create API requests that are more likely to succeed at runtime.

**Comment by nanotellez** [comment] 2020-02-05 23:20
That makes a lot of sense. Thanks for clarifying. Perhaps (once some of that friction is worked out) there could be some examples of Read/Modify/Write patterns worked out with the SDK provided in the Readme file (right now the example provided focuses on user management only).

**Comment by jkaster** [comment] 2020-02-05 23:22
We will continue to add and update Python SDK examples in the [SDK Examples](https://github.com/looker-open-source/sdk-examples/tree/master/python) repository. Adding link to that example in the Readme is a good idea, but we don't want the readme to get so long people don't actually read it :)

**Comment by nanotellez** [comment] 2020-02-06 00:47
Agree 100%. I didn't realize there was an SDK Examples repo, hence my reference to the example in the Readme. If it were me, I would remove that example from there and replace it with the link to the examples repo.

Thanks for all the explanations, and for all the work you guys are doing!

**Comment by jkaster** [comment] 2020-02-06 01:46
Thanks for the reply. We'll definitely take your suggestion and put a link in the package readme that points to the examples repository, now that we actually have examples in that repository. I appreciate your patience as we work on the ripple effects.

**Comment by danieldiamond** [comment] 2022-08-09 11:29
Hi @jkaster, I am looking to store the dashboard information locally in a json object using python, however I'm running into the issues outlined above i.e. that the object contains nested objects that cannot be serialized. This happens when I try to convert the dashboard data into a dict. 
Do you have any suggested workarounds?

e.g. this is failing in python
```python
data = sdk.dashboard(dashboard_id, "", None)
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(str(data), f, ensure_ascii=False, indent=4)
```

in golang, this works
```go
bytes, err := json.MarshalIndent(dashboard, "", "  ")
...
err = ioutil.WriteFile(fileName, bytes, 0644)
```

I'm wondering if there's an equivalent for python

**Comment by joeldodge79** [comment] 2022-08-09 23:47
@danieldiamond  what error do you get? I see you're passing `str(data)` as the first arg to `json.dump`. all the response objects implement a [dictionary-like interface](https://github.com/looker-open-source/sdk-codegen/blob/ae59b956a5f42dcdd5aa9b4c3d0da1836129a932/python/looker_sdk/rtl/model.py#L46) but I don't know if that's enough for json.dump

**Comment by danieldiamond** [comment] 2022-08-10 03:23
Hi @joeldodge79 ah yeah that was an old code snippet. Tbh I've tried all variations including (and mostly) `dict(data)`. The issue is simply that the object contains nested objects and that the python SDK for some reason casts the response, [see here](https://github.com/looker-open-source/sdk-codegen/blob/main/python/looker_sdk/sdk/api40/methods.py#L4158-L4167), which is explained at the start of this issue. In contrast to the golang SDK which returns the response, [see here](https://github.com/looker-open-source/sdk-codegen/blob/main/go/sdk/v4/methods.go#L2644-L2651).
This is really frustrating as I'd like a JSON representation of the dashboard in python.

**Comment by nanotellez** [comment] 2022-08-10 16:59
@danieldiamond I haven't worked with this stuff in almost two years, so take this with a huge grain of salt. My workaround when I "resolved" my issue (as noted above) was to use the `response.__dict__`. Perhaps if you use that in your `json.dump` you might get what you need?

**Comment by jeffhuth-windriver** [comment] 2022-12-09 18:58
Here is a way that worked for me.

`import looker_sdk
import json
from json import JSONEncoder
import jsonpickle

sdk = looker_sdk.init40() 
dashboards = sdk.search_dashboards(id="1240")

# Loop over dashbaords
for dashboard in dashboards:
    # Convert dashboard class object to dictionary
    dashboard_dict = json.loads(jsonpickle.encode(dashboard, unpicklable=False))`

**Comment by pfrisella** [comment] 2023-02-22 20:38
This is effectively working as intended so I'm closing for now. A feature request can be opened for review if needed but as mentioned earlier the intention is to return a typed object.

**Closed** 2023-02-28 17:49 UTC
Labels: python, p3
